# -*- coding: utf-8 -*-
"""
GitHub Actions 专用版 - 自动化源健康检查
功能：每日凌晨 3 点自动检测并报告状态
注意：此版本不修改 config.json，只做检测和生成报告
"""
import json
import requests
from datetime import datetime

CONFIG_PATH = 'config.json'
GUARDS_DB_PATH = 'all_guard_classes.json'

def log(msg):
    """打印日志到控制台和 GITHUB_STEP_SUMMARY"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_msg = f'[ {timestamp} ] {msg}'
    print(log_msg)
    
    # 同时写入总结文件
    with open('github_summary.md', 'a', encoding='utf-8') as f:
        f.write(f'{log_msg}\n')

def main():
    log("=" * 60)
    log("GitHub Actions - Auto Source Health Check")
    log("=" * 60)
    
    try:
        # 1. 加载配置
        log("Loading config...")
        with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
            config = json.load(f)
        
        total_sites = len(config.get('sites', []))
        type3_sites = [s for s in config['sites'] if s.get('type') == 3]
        guard_count = len([s for s in type3_sites if 'Guard' in s.get('api', '')])
        
        log(f"Total sites: {total_sites}")
        log(f"Type-3 (Spider) sites: {len(type3_sites)}")
        log(f"Guard class count: {guard_count}")
        
        # 2. 检查 Guard 类数据库是否存在
        try:
            with open(GUARDS_DB_PATH, 'r', encoding='utf-8') as f:
                guards_db = json.load(f)
            
            all_guards = guards_db.get('all_guards', [])
            categories = guards_db.get('categories', {})
            
            log(f"Available Guard classes: {len(all_guards)}")
            
            # 统计各类别的数量
            for cat_name, cat_list in categories.items():
                log(f"  {cat_name}: {len(cat_list)}")
                
        except FileNotFoundError:
            log("WARNING: Guard database not found!")
            all_guards = []
        
        # 3. 简单测试几个核心 API 是否可达
        log("\nTesting core APIs connectivity...")
        test_urls = [
            ("Source Config", "https://9280.kstore.vip/newwex.json"),
            ("GitHub Pages Config", "https://abu168888.github.io/tvbox-config/config.json"),
        ]
        
        healthy_count = 0
        for name, url in test_urls:
            try:
                r = requests.get(url, timeout=15)
                if r.status_code == 200:
                    log(f"✓ {name}: OK ({r.status_code})")
                    healthy_count += 1
                else:
                    log(f"✗ {name}: HTTP {r.status_code}")
            except Exception as e:
                log(f"✗ {name}: ERROR - {str(e)[:50]}")
        
        # 4. 生成最终报告
        log("\n" + "=" * 60)
        log("Health Check Summary")
        log("=" * 60)
        log(f"Check time: {datetime.now().isoformat()}")
        log(f"Status: {'HEALTHY' if healthy_count > 0 else 'UNHEALTHY'}")
        log(f"Core APIs tested: {healthy_count}/{len(test_urls)} passed")
        log(f"\nNext action: None (this version only monitors)")
        
        # 更新 GitHub Step Summary
        with open('github_summary.md', 'w', encoding='utf-8') as f:
            f.write("# 📊 Auto Source Health Check Report\n\n")
            f.write(f"**Run ID:** `{'{github.run_id}'}`\n\n")
            f.write(f"**Timestamp:** `{datetime.now().isoformat()}`\n\n")
            f.write("## 📈 Statistics\n\n")
            f.write(f"- Total Sites: `{total_sites}`\n")
            f.write(f"- Type-3 Spider Sites: `{len(type3_sites)}`\n")
            f.write(f"- Guard Classes Used: `{guard_count}`\n")
            if all_guards:
                f.write(f"- Available Guard Pool: `{len(all_guards)}`\n")
            f.write(f"\n## 🔍 Core API Tests\n\n")
            f.write(f"- Healthy APIs: `{healthy_count}/{len(test_urls)}`\n")
            f.write(f"- Status: `{'✅ HEALTHY' if healthy_count > 0 else '❌ UNHEALTHY'}'\n")
            f.write(f"\n---\n*Report generated by Auto Source Manager v1.0*\n")
        
        log("\n[SUCCESS] Report saved to github_summary.md")
        
    except Exception as e:
        log(f"[ERROR] Unexpected error: {e}")
        import traceback
        log(traceback.format_exc())
        return 1
    
    return 0

if __name__ == '__main__':
    exit(main())
